apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raft
spec:
  serviceName: "raft"
  replicas: 3
  selector:
    matchLabels:
      app: raft
  template:
    metadata:
      labels:
        app: raft
    spec:
      containers:
      - name: raft
        image: raft-kv:latest
        command: ["python3", "RaftNode.py", "$(POD_NAME).raft", "5001"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: raft-config